In [1]:
import numpy as np

In [3]:
zeroArr = np.zeros(10)
print(zeroArr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [4]:
zeroArr = np.ones10)
print(zeroArr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

In [5]:
zeroArr = zeroArr.astype(int)
print(zeroArr)

[1 1 1 1 1 1 1 1 1 1]

In [6]:
zeroArr = np.ones(10)
print(zeroArr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

In [11]:
allneed = np.full(15,5)
print(allneed)

[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]

In [ ]:
treeDayArray = np.array()

In [2]:
dataframe = [['pomme', 'annanabanana '], ["Mango", "Orange"], ['Freize', 'Kiwi']]

In [5]:
import pandas as pd
monDataFrame = pd.DataFrame(dataframe, columns=["Fruits 1", "Fruits 2"])
monDataFrame

  Fruits 1       Fruits 2
0    pomme  annanabanana
1    Mango         Orange
2   Freize           Kiwi

In [4]:
monDataFrame

        0              1
0   pomme  annanabanana
1   Mango         Orange
2  Freize           Kiwi

In [11]:
import numpy as np
maList = np.array([[0,1], [2,3], [4,5]])

In [14]:
myDataFrame2 = pd.DataFrame(maList, columns=['Premier col' ,'Deuxieme col'])
myDataFrame2

   Premier col  Deuxieme col
0            0             1
1            2             3
2            4             5

In [16]:
maDictionnaire = {
    'Fruits':["Pomme", 'Banana', 'Orange'],
    'Couleur' : ["Rouge", 'Jaune', 'Orange']
}

In [18]:
monDataFrame3 = pd.DataFrame(maDictionnaire)
monDataFrame3

   Fruits Couleur
0   Pomme   Rouge
1  Banana   Jaune
2  Orange  Orange

In [20]:
df = pd.read_csv('cereals.csv')
df

                        name  calories  protein  vitamins     rating
0                  100% Bran        70        4        25  68.402973
1          100% Natural Bran       120        3         0  33.983679
2                   All-Bran        70        4        25  59.425505
3  All-Bran with Extra Fiber        50        4        25  93.704912
4             Almond Delight       110        2        25  34.384843
5    Apple Cinnamon Cheerios       110        2        25  29.509541
6                Apple Jacks       110        2        25  33.174094
7                    Basic 4       130        3        25  37.038562
8                  Bran Chex        90        2        25  49.120253
9                Bran Flakes        90        3        25  53.313813

In [21]:
df.head(3)

                name  calories  protein  vitamins     rating
0          100% Bran        70        4        25  68.402973
1  100% Natural Bran       120        3         0  33.983679
2           All-Bran        70        4        25  59.425505

In [22]:
df.tail(3)

          name  calories  protein  vitamins     rating
7      Basic 4       130        3        25  37.038562
8    Bran Chex        90        2        25  49.120253
9  Bran Flakes        90        3        25  53.313813

In [23]:
df.describe()

         calories    protein   vitamins     rating
count   10.000000  10.000000  10.000000  10.000000
mean    95.000000   2.900000  22.500000  49.205817
std     25.495098   0.875595   7.905694  20.315297
min     50.000000   2.000000   0.000000  29.509541
25%     75.000000   2.000000  25.000000  34.083970
50%    100.000000   3.000000  25.000000  43.079408
75%    110.000000   3.750000  25.000000  57.897582
max    130.000000   4.000000  25.000000  93.704912

In [24]:
df[1:5]

                        name  calories  protein  vitamins     rating
1          100% Natural Bran       120        3         0  33.983679
2                   All-Bran        70        4        25  59.425505
3  All-Bran with Extra Fiber        50        4        25  93.704912
4             Almond Delight       110        2        25  34.384843

In [25]:
df[['name', 'rating']]

                        name     rating
0                  100% Bran  68.402973
1          100% Natural Bran  33.983679
2                   All-Bran  59.425505
3  All-Bran with Extra Fiber  93.704912
4             Almond Delight  34.384843
5    Apple Cinnamon Cheerios  29.509541
6                Apple Jacks  33.174094
7                    Basic 4  37.038562
8                  Bran Chex  49.120253
9                Bran Flakes  53.313813

In [27]:
nineRow = [False, True, False, False, False, True, False, False, True, True]
df[nineRow]

                      name  calories  protein  vitamins     rating
1        100% Natural Bran       120        3         0  33.983679
5  Apple Cinnamon Cheerios       110        2        25  29.509541
8                Bran Chex        90        2        25  49.120253
9              Bran Flakes        90        3        25  53.313813

In [29]:
condition = df['calories'] > 100
df[condition]

                      name  calories  protein  vitamins     rating
1        100% Natural Bran       120        3         0  33.983679
4           Almond Delight       110        2        25  34.384843
5  Apple Cinnamon Cheerios       110        2        25  29.509541
6              Apple Jacks       110        2        25  33.174094
7                  Basic 4       130        3        25  37.038562

In [32]:
df[(df['calories'] > 90) & (df['protein'] < 4)]

                      name  calories  protein  vitamins     rating
1        100% Natural Bran       120        3         0  33.983679
4           Almond Delight       110        2        25  34.384843
5  Apple Cinnamon Cheerios       110        2        25  29.509541
6              Apple Jacks       110        2        25  33.174094
7                  Basic 4       130        3        25  37.038562

In [34]:
df.loc[0, 'name']

'100% Bran'

In [35]:
df.loc[[0],['name']]

        name
0  100% Bran

In [37]:
df.loc[0:4]

                        name  calories  protein  vitamins     rating
0                  100% Bran        70        4        25  68.402973
1          100% Natural Bran       120        3         0  33.983679
2                   All-Bran        70        4        25  59.425505
3  All-Bran with Extra Fiber        50        4        25  93.704912
4             Almond Delight       110        2        25  34.384843

In [38]:
df.loc[0:4, 'name': 'protein']

                        name  calories  protein
0                  100% Bran        70        4
1          100% Natural Bran       120        3
2                   All-Bran        70        4
3  All-Bran with Extra Fiber        50        4
4             Almond Delight       110        2

In [39]:
df.loc[[5,8], 'name': 'protein']

                      name  calories  protein
5  Apple Cinnamon Cheerios       110        2
8                Bran Chex        90        2

In [43]:
df.iloc[8,0]

'Bran Chex'

In [46]:
df.iloc[[8], [4]]

      rating
8  49.120253

In [45]:
df

                        name  calories  protein  vitamins     rating
0                  100% Bran        70        4        25  68.402973
1          100% Natural Bran       120        3         0  33.983679
2                   All-Bran        70        4        25  59.425505
3  All-Bran with Extra Fiber        50        4        25  93.704912
4             Almond Delight       110        2        25  34.384843
5    Apple Cinnamon Cheerios       110        2        25  29.509541
6                Apple Jacks       110        2        25  33.174094
7                    Basic 4       130        3        25  37.038562
8                  Bran Chex        90        2        25  49.120253
9                Bran Flakes        90        3        25  53.313813

In [47]:
df.iloc[0:5]

                        name  calories  protein  vitamins     rating
0                  100% Bran        70        4        25  68.402973
1          100% Natural Bran       120        3         0  33.983679
2                   All-Bran        70        4        25  59.425505
3  All-Bran with Extra Fiber        50        4        25  93.704912
4             Almond Delight       110        2        25  34.384843

In [52]:
df.iloc[1:5, 0:3]

                        name  calories  protein
1          100% Natural Bran       120        3
2                   All-Bran        70        4
3  All-Bran with Extra Fiber        50        4
4             Almond Delight       110        2

In [53]:
df

                        name  calories  protein  vitamins     rating
0                  100% Bran        70        4        25  68.402973
1          100% Natural Bran       120        3         0  33.983679
2                   All-Bran        70        4        25  59.425505
3  All-Bran with Extra Fiber        50        4        25  93.704912
4             Almond Delight       110        2        25  34.384843
5    Apple Cinnamon Cheerios       110        2        25  29.509541
6                Apple Jacks       110        2        25  33.174094
7                    Basic 4       130        3        25  37.038562
8                  Bran Chex        90        2        25  49.120253
9                Bran Flakes        90        3        25  53.313813

In [56]:
df.iloc[[0,7,3], 0:4]

                        name  calories  protein  vitamins
0                  100% Bran        70        4        25
7                    Basic 4       130        3        25
3  All-Bran with Extra Fiber        50        4        25

In [57]:
df

                        name  calories  protein  vitamins     rating
0                  100% Bran        70        4        25  68.402973
1          100% Natural Bran       120        3         0  33.983679
2                   All-Bran        70        4        25  59.425505
3  All-Bran with Extra Fiber        50        4        25  93.704912
4             Almond Delight       110        2        25  34.384843
5    Apple Cinnamon Cheerios       110        2        25  29.509541
6                Apple Jacks       110        2        25  33.174094
7                    Basic 4       130        3        25  37.038562
8                  Bran Chex        90        2        25  49.120253
9                Bran Flakes        90        3        25  53.313813

In [58]:
df.loc[10] = ["Waby", 120, 4, 30, 47.46839]

In [59]:
df

                         name  calories  protein  vitamins     rating
0                   100% Bran        70        4        25  68.402973
1           100% Natural Bran       120        3         0  33.983679
2                    All-Bran        70        4        25  59.425505
3   All-Bran with Extra Fiber        50        4        25  93.704912
4              Almond Delight       110        2        25  34.384843
5     Apple Cinnamon Cheerios       110        2        25  29.509541
6                 Apple Jacks       110        2        25  33.174094
7                     Basic 4       130        3        25  37.038562
8                   Bran Chex        90        2        25  49.120253
9                 Bran Flakes        90        3        25  53.313813
10                       Waby       120        4        30  47.468390

In [64]:
df['New Col'] = ['A', 'B', 'C','D', 'E', 'F', 'G', 'H','I', 'j', 'K']
df

                         name  calories  protein  vitamins     rating New Col
0                   100% Bran        70        4        25  68.402973       A
1           100% Natural Bran       120        3         0  33.983679       B
2                    All-Bran        70        4        25  59.425505       C
3   All-Bran with Extra Fiber        50        4        25  93.704912       D
4              Almond Delight       110        2        25  34.384843       E
5     Apple Cinnamon Cheerios       110        2        25  29.509541       F
6                 Apple Jacks       110        2        25  33.174094       G
7                     Basic 4       130        3        25  37.038562       H
8                   Bran Chex        90        2        25  49.120253       I
9                 Bran Flakes        90        3        25  53.313813       j
10                       Waby       120        4        30  47.468390       K

In [65]:
df

                         name  calories  protein  vitamins     rating New Col
0                   100% Bran        70        4        25  68.402973       A
1           100% Natural Bran       120        3         0  33.983679       B
2                    All-Bran        70        4        25  59.425505       C
3   All-Bran with Extra Fiber        50        4        25  93.704912       D
4              Almond Delight       110        2        25  34.384843       E
5     Apple Cinnamon Cheerios       110        2        25  29.509541       F
6                 Apple Jacks       110        2        25  33.174094       G
7                     Basic 4       130        3        25  37.038562       H
8                   Bran Chex        90        2        25  49.120253       I
9                 Bran Flakes        90        3        25  53.313813       j
10                       Waby       120        4        30  47.468390       K

In [68]:
df.drop('New Col', axis = 1, inplace = True)

In [69]:
df

                         name  calories  protein  vitamins     rating
0                   100% Bran        70        4        25  68.402973
1           100% Natural Bran       120        3         0  33.983679
2                    All-Bran        70        4        25  59.425505
3   All-Bran with Extra Fiber        50        4        25  93.704912
4              Almond Delight       110        2        25  34.384843
5     Apple Cinnamon Cheerios       110        2        25  29.509541
6                 Apple Jacks       110        2        25  33.174094
7                     Basic 4       130        3        25  37.038562
8                   Bran Chex        90        2        25  49.120253
9                 Bran Flakes        90        3        25  53.313813
10                       Waby       120        4        30  47.468390

In [73]:
df.sort_values(by= 'calories')

                         name  calories  protein  vitamins     rating
3   All-Bran with Extra Fiber        50        4        25  93.704912
0                   100% Bran        70        4        25  68.402973
2                    All-Bran        70        4        25  59.425505
8                   Bran Chex        90        2        25  49.120253
9                 Bran Flakes        90        3        25  53.313813
4              Almond Delight       110        2        25  34.384843
5     Apple Cinnamon Cheerios       110        2        25  29.509541
6                 Apple Jacks       110        2        25  33.174094
1           100% Natural Bran       120        3         0  33.983679
10                       Waby       120        4        30  47.468390
7                     Basic 4       130        3        25  37.038562

In [74]:
df.sort_values(by= 'calories', ascending=False)

                         name  calories  protein  vitamins     rating
7                     Basic 4       130        3        25  37.038562
1           100% Natural Bran       120        3         0  33.983679
10                       Waby       120        4        30  47.468390
4              Almond Delight       110        2        25  34.384843
5     Apple Cinnamon Cheerios       110        2        25  29.509541
6                 Apple Jacks       110        2        25  33.174094
8                   Bran Chex        90        2        25  49.120253
9                 Bran Flakes        90        3        25  53.313813
0                   100% Bran        70        4        25  68.402973
2                    All-Bran        70        4        25  59.425505
3   All-Bran with Extra Fiber        50        4        25  93.704912

In [76]:
mydf = {
    'sexe' : ['Female', 'Male', 'Female', 'Male'],
    'score': [90, 120, 68, 80]
}
mydf = pd.DataFrame.from_dict(mydf)

In [77]:
mydf

     sexe  score
0  Female     90
1    Male    120
2  Female     68
3    Male     80

In [80]:
mydf.groupby(mydf['sexe']).mean()

        score
sexe
Female   79.0
Male    100.0